### ISSUE TITLE
Channel auf Routerseite anzeigen

### ISSUE THREAD

**Issue by ChristianDresel** [FreifunkFranken/fff-monitoring#104]
Da mit den dezentralen Hoods und vorallem später mit den Sectorfiles der Wifi-Kanal nicht mehr eindeutig ist, wäre es toll wenn dieser auf der Routerseite angezeit wird. Am besten getrennt nach 2,4GHz und 5GHz (und die Option offen lassen das irgendwann zu erweitern)

Achtung:
Der Kanal ist aktuell noch nicht in der Nodewatcher JSON enthalten, ich mache dazu gleich ein Mantis Ticket auf --> https://mantis.freifunk-franken.de/view.php?id=81

**Comment by adridolf** [comment]
Finde ich gut, hat aber erstmal niedrige Priorität.

**Comment by adridolf** [comment]
Die Funktion ist ab sofort eingebaut. Die Daten werden bei den jeweiligen Netzwerk-Interfaces angezeigt, also der Kanal für 2.4 GHz bei w2ap, w2mesh, w2configap. Der entsprechende Patch ist im Patchwork zu finden:
https://pw.freifunk-franken.de/patch/728/

Aus aktuellem Anlass habe ich weitere Parameter mit eingebaut, sodass nun bei Routern mit entsprechender nodewatcher-Version auch die SSID und der Typ (AP, Mesh, IBSS, ...) angezeigt werden. Bereits enthalten im XML ist die Tx-Power, diese wird nun auch bei "alten" Routern angezeigt.

Beispiel neu:
https://monitoring.freifunk-franken.de/mac/f0:9f:c2:dc:c3:38

Beispiel alt:
https://monitoring.freifunk-franken.de/mac/84:16:f9:5b:87:6c
