### ISSUE TITLE
Zeige mehr Events auf Routerdetailseite

### ISSUE THREAD

**Issue by adridolf** [FreifunkFranken/fff-monitoring#105]
Ich würde gerne mehr Events auf der Routerdetailseite zeigen als die jetzigen fünf.

Hat jemand eine Idee, wie man das manchen kann, ohne das Design zu zerstören?

**Comment by asdil12** [comment]
Scrollbalken

**Comment by adridolf** [comment]
Mit Scrollbalken gelöst. Es werden jetzt max. 25 Events angezeigt. Damit das neueste Event sofort ersichtlich ist, wurde die Reihenfolge invertiert.

Da ich nicht in der Lage war, ein funktionierendes Design mit height:100% zu bauen, habe ich die Höhe in Pixel hardgecodet.

https://github.com/FreifunkFranken/fff-monitoring/commit/6d9598be714c3ed25ae142755ccee3a1feb9ac78
