### ISSUE TITLE
Use default string instead of empty hostname

### ISSUE THREAD

**Issue by adridolf** [FreifunkFranken/fff-monitoring#109]

**Comment by asdil12** [comment]
maybe use the router mac

**Comment by adridolf** [comment]
Eigentlich ist das ein ganz seltener Spezialfall. Wichtig ist der nur deshalb, weil es ohne Routernamen keinen Link zum Router gibt.
Ich würde daher für diesen eher etwas Richtung "GibMirEinenNamen" benutzen ...

**Comment by adridolf** [comment]
Erledigt.
