### ISSUE TITLE
Rechtsklick Karte Koordinaten

### ISSUE THREAD

**Issue by ChristianDresel** [FreifunkFranken/fff-monitoring#111]
adrianschmutzler (IRC)
äh, mach mal bitte für mich einen eintrag im github, dass man per rechtsklick auf die karte die koordinaten bekommen soll

**Comment by adridolf** [comment]
Die Koordinaten werden nun immer dann angezeigt, wenn NICHT auf einen Router geklickt wird. Die Rechtsklick-Funktion bleibt unberührt.

Da die Layer abgeschaltet werden können sind so auch Punkte unter den Router-Markern erreichbar, wenn diese abgeschaltet werden.

https://github.com/FreifunkFranken/fff-monitoring/commit/621cf35f103e35e42431a1ba4c78267f80a6b7a7

**Comment by fblaese** [comment]
Kann man dieses Feature irgendwie Opt-In machen?
Ich klicke normal neben Router, um das Routerfenster wieder los zu werden.

**Comment by adridolf** [comment]
Das Popup hat oben rechts ein X zum Schließen.

**Comment by fblaese** [comment]
Das ist mir durchaus bewusst, aber das x ist so klein und die Gewohnheit sagt mir einfach, dass man Dinge deselektiert, wenn man auf leere Flächen neben dem Markierten klickt (siehe auch andere Kartenimplementierungen)

Möglicherweise ist auch eine Lösung denkbar, bei der beim 1. Klick deselektiert wird und erst beim 2. Klick die Koordinaten auftachen (falls vorher ein Popup geöffnet war)

**Comment by adridolf** [comment]
Mal überlegen ...

**Comment by asdil12** [comment]
Ich würde prüfen, ob schon ein Pop-up offen ist, und nur die Koordinaten anzeigen, wenn noch keins offen ist.

**Comment by asdil12** [comment]
Ah - genau das, was @fblaese vorgeschlagen hat

**Comment by adridolf** [comment]
Es gibt offenbar keine einfache Methode um zu prüfen, ob ein Popup offen ist. Schließen an sich ist kein Problem, aber die Prüfung.

**Comment by asdil12** [comment]
Dann muss man die Info eben beim Pop-up öffnen und schließen in einer variable speichern.

Ansonsten könnte man per CSS selector checken, ob ein Pop-up da ist.

**Comment by adridolf** [comment]
Braucht eigtl jemand den doubleclickzoom? ich überlege gerade, die koordinaten einfach nur bei doppelklick anzuzeigen.

**Comment by asdil12** [comment]
Du kannst mit `$("a.leaflet-popup-close-button").length` prüfen, ob ein popup offen ist - dann ist der Wert `1`, sonst `0`

**Comment by asdil12** [comment]
Den doubleclick würde ich so lassen - zumindest ich verwende den oft.

**Comment by adridolf** [comment]
Habe es jetzt so gelöst, das bei offenem Popup der erste Klick schließt und der zweite die Koordinaten anzeigt. Beim Klick auf einen Router geht sofort ein neues Popup auf.

Musste über eine manuelle Variable gehen, alles andere hat aus verschiedenen Gründen nicht funktioniert. Sollte damit erledigt sein.
