### ISSUE TITLE
Perma Link Zugriff auf ?json

### ISSUE THREAD

**Issue by ChristianDresel** [FreifunkFranken/fff-monitoring#113]
Hallo

es ist bei den "normalen" Links (z.b. https://monitoring.freifunk-franken.de/routers/4400 ) möglich, mit ?json als Anhang sich die json anzeigen zu lassen also:

https://monitoring.freifunk-franken.de/routers/4400?json

leider funktioniert dies bei den Perma-Link nicht:

https://monitoring.freifunk-franken.de/mac/64:66:b3:de:f5:cd?json

wäre schön wenn man das nachrüsten kann.

mfg

Christian

**Comment by adridolf** [comment]
@asdil12  Weißt du zufällig aus dem Stegreif, wie man da ALLE GET-Parameter weiterreichen kann (url_for)?

Der Code steht hier:
https://github.com/FreifunkFranken/fff-monitoring/blob/master/ffmap/web/application.py#L65

**Comment by asdil12** [comment]
url_for('foo', **hierdasdictmitdengetparametern)

Aber pass auf, dass das keine Sicherheitslücken mitbringt.

Am 14. Januar 2018 19:23:42 MEZ schrieb Adrian Schmutzler <notifications@github.com>:
>@asdil12  Weißt du zufällig aus dem Stegreif, wie man da ALLE
>GET-Parameter weiterreichen kann (url_for)?
>
>Der Code steht hier:
>https://github.com/FreifunkFranken/fff-monitoring/blob/master/ffmap/web/application.py#L65

**Comment by adridolf** [comment]
Ist gefixt: a72931c215e0a2775d9a7e19421799cc57f75467

Habe es jetzt doch nur für die einzelnen bekannten Parameter implementiert. Allerdings kann ich keine Parameter ohne value setzen, daher json=1 ...
