### ISSUE TITLE
Alfred Proxy

### ISSUE THREAD

**Issue by asdil12** [FreifunkFranken/fff-monitoring#12]
- Python Package for Alfred Proxy
- Create Hook API (i.e. `/etc/alfred/hook.d/`) with subclasses of API class
  - Port monitoring push part to hook

**Comment by adrianschmutzler** [comment]
@asdil12: Worum ging es hier?
Weiteres Verfahren:
- Relevant: Offen lassen und erklären
- Unklar: offen lassen
- Irrelevant: Schließen und begraben

**Comment by asdil12** [comment]
Das ist vmtl eh egal, da meine Python-implementierung vom alfred-proxy zugunsten der c-implementierung nicht mehr verwendet wird.
