### ISSUE TITLE
Airtime in der Systembox anzeigen

### ISSUE THREAD

**Issue by ChristianDresel** [FreifunkFranken/fff-monitoring#124]
In der Systembox unter Client sollte die aktuelle Airtimebelastung mit angezeigt werden damit es das selbe System wie bei den Clients ist (Graph unten, aktueller Wert oben).

Damit die Kästen gleich groß bleiben evtl. dazu die Karte vergrößern

**Comment by adridolf** [comment]
Erledigt.
