### ISSUE TITLE
Verbindungsstärke in MAP als Overlay anzeigen lassen?

### ISSUE THREAD

**Issue by manuelreiter** [FreifunkFranken/fff-monitoring#126]
Hi,

wäre es möglich in die Freifunkmap zusätzlich zu den BATMAN-Linien ein Overlay für die Verbindungsstärke anzeigen zu lassen?

greetz,
manu.

**Comment by manuelreiter** [comment]
*Signalstärke

**Comment by adridolf** [comment]
Beschreibe mal ein bisschen genauer, was du dir vorstellst. Die Signalstärke ist ja einseitig und hat zunächst nichts mit einer Verbindung zu tun.

**Comment by manuelreiter** [comment]
Die Linien die gezeichnet werden sind ja nur die Verbindungen die BATMAN aufbaut. Schön wäre es aber, wenn es noch ein Overlay geben würde, das die Signalstärke der in der Nähe befindlichen freifunk router anzeigt. Für die Farbgebung dann nicht die BATMAN bewertung von 0-255 sondern die Signalstärke in db von -0 bis -90 oder so.  So bekommt man eine eine Übersicht der Routerverbindungen untereinander, unabhängig davon welche Route BATMAN benutzt. (hoffentlich hab ich mich verständlich ausgedrückt)

**Comment by adridolf** [comment]
D.h. Router A zeigt den Link zu B anhand von Bs Signalstärke in dB an?
Wenn ich das richtig verstehe, müssten wir dazu alle 5 Min. einen wifiscan machen und diese Daten in den nodewatcher stecken? Oder gibt es irgendwas, was schon da ist und man nutzen kann?

**Comment by manuelreiter** [comment]
Genau, Bs Signalstärke in dB.
Dachte die Daten würden schon übergeben werden. Wäre aber sinnvoll zum Routeraufstellen...
Weiss garnicht ob bei nem wifiscan die Clients nicht kurzzeitig  getrennt werden?!?

**Comment by manuelreiter** [comment]
evtl kommt man mit batctl an die nachbarknoten die in reichweite aber nicht verbunden sind ran?!?

**Comment by adridolf** [comment]
das ist ja im Prinzip das, was wir auswerten.

https://github.com/FreifunkFranken/firmware/blob/master/src/packages/fff/fff-nodewatcher/files/usr/sbin/nodewatcher

Ab Zeile 225 ...

Also wissen wir das, was in dem File steht:
/sys/kernel/debug/batman_adv/bat0/originators

Kannst ja mal auf dem Router nachkucken, ob dir das hilft.

**Comment by manuelreiter** [comment]
also bei routern mit uplink kommt man damit an eine brauchbare liste:
cat /sys/kernel/debug/batman_adv/bat0/originators | grep w2mesh
(oder hab ich was übersehen)

wies bei router die nur meshen aussieht hab ich noch nicht probiert.

**Comment by adridolf** [comment]
Und das ist die Liste, die wir auswerten. D.h. genau daraus machen wir die Linien, die jetzt schon da sind. (0-255)
Für deine dB-Idee müsste man eine völlig neue Auswertung bauen und implementieren.

**Comment by adridolf** [comment]
Nach der bisherigen Diskussion ist das zwar eine schöne Idee, aber mit unverhältnismäßigem Aufwand in der Routerfirmware (nodewatcher) verbunden.

Entsprechend würde ich das Ticket wieder schließen. Falls es irgendwann brauchbare nodewatcher-Daten dazu gibt, können wir gerne nochmal drüber reden.

Widerspruch?
