### ISSUE TITLE
"Coordinates" Fenster entfernen

### ISSUE THREAD

**Issue by RedDog99** [FreifunkFranken/fff-monitoring#139]
Wäre es möglich das "Coordinates" Fenster zu entfernen? Das stört ziemlich und bringt keinen Mehrwert. Insbesondere auf Touch-Display basierten Geräten ist die Usability total hin mit dem Ding.

**Comment by adridolf** [comment]
Tschuldigung, aber was ist das "Coordinates" Fenster? Meinst du das Popup in der Karte?

**Comment by RedDog99** [comment]
Am Montag, den 05.03.2018, 13:00 -0800 schrieb Adrian Schmutzler:
> Tschuldigung, aber was ist das "Coordinates" Fenster? Meinst du das
> Popup in der Karte?

Ja, das taucht so ein Fenster auf, wenn man den Knoten auf der Karte
nicht ganz exakt getroffen hat.

**Comment by adridolf** [comment]
Ich habe das extra eingebaut, weil ich regelmäßig Koordinaten für Router von Hand eingebe (per SSH) und es sehr lästig war, dann die Gebäudezeichnung vom Monitoring mit denen von Google abzugleichen, damit ich an die richtigen Koordinaten komme.
Ich hatte allerdings bisher auch keine Probleme am Handy.

**Comment by adridolf** [comment]
Ich habe es gerade mal an meinem Handy probiert und finde das Verhalten nachvollziehbar (also er scrollt, wenn er scrollen soll und macht ein Popup auf, wenn er ein Popup aufmachen soll).

Man könnte überlegen, ob man das Popup erst nach einem Klick mehr aufmacht?

**Comment by adrianschmutzler** [comment]
AlexG (aus E-Mail):

Aaalso:
Ich nutze Android den Chrome Browser.

Wenn ich normal auf die Map gehe, drauf bleibe und zur Seite schiebe, passiert nichts. -> alles gut.

Wenn ich kurz tippe und wieder weg gehe, poppt das Fenster mit den Koordinaten auf. -> vermutlich auch so gedacht und kontrollierbar.

Wenn ich nun allerdings Doppel dippe um zu zoomen (ist für mich und viele andere einfach Standart) öffnet sich das Koordinaten Popup auch wieder was sehr nervig sein kann. Wenn man es dann weg klicken will und das x nicht genau trifft öffnet sich das nächste Koordinaten Fenster und verschiebt in den Außenbereichen das Zentrum.


Ich weiß ist schwierig zu programmieren da ein Doppel Tap ja eigentlich nur zwei einfache Taps sind und somit die Koordinaten Anzeigen sollen ... Könnte man die Koordinaten Geschichte im drop down Menü evtl mit nem Haken aktivieren und deaktivieren? Dann kann ich's am Smartphone aus lassen, am Rechner, wo es nützlich ist, dann per Klick aktivieren.

**Comment by adrianschmutzler** [comment]
Der kritische Punkt ist der Doppeltap: Den benutze ich nie, und deshalb geht es bei mir. Sobald man den Doppeltap macht, geht aber irgendwie alles kaputt.

Ich werde mir das mal in Ruhe ansehen.

Persönlich mag ich die Idee mit dem Aktivieren per Haken, da könnte ich gut damit leben, auch mit default:off. Mal sehen, wie einfach das zu bauen ist.

**Comment by asdil12** [comment]
Was mir auch noch aufgefallen ist: wenn man das layer Menü am Handy aufmacht und anschließend auf die Karte tippt, um es wieder zu schließen, geht auch ein Pop-up auf.

**Comment by adrianschmutzler** [comment]
Hab jetzt die Lösung mit dem Aktivieren per Haken implementiert. Ihr könnt ja mal testen, ob es euch jetzt so taugt. Vorher Cache leeren mit Strg+F5!

**Comment by asdil12** [comment]
Am PC funktioniert es schonmal gut.

**Comment by adrianschmutzler** [comment]
-> Resolved.
