### ISSUE TITLE
Monitoring-Karte: unterschiedliche Farben für Hoodgrenzen

### ISSUE THREAD

**Issue by Nautic** [FreifunkFranken/fff-monitoring#159]
Wenn in der Monitoring-Karte die Hoodgrenzen von V1 beziehungsweise V2 unterschiedliche Farben hätten, könnte man sie intuitiver erkennen und vergleichen.
(hat aber nur eine sehr niedrige Prio ;-) )

**Comment by adrianschmutzler** [comment]
Will be merged soon.

**Comment by Nautic** [comment]
Farbe #73b9ff für Hood-V1 im Wiki eingetragen:
https://wiki.freifunk-franken.de/w/Monitoring#Map
