### ISSUE TITLE
Link in Monitoring-Karte zur Doku im Wiki

### ISSUE THREAD

**Issue by Nautic** [FreifunkFranken/fff-monitoring#164]
zwei Verbesserungsvorschläge für das Monitoring:
- in der Karte die Wikiseite verlinken
  https://wiki.freifunk-franken.de/w/Monitoring
- in den Monitoring-Seiten die Wikiseite verlinken
  https://wiki.freifunk-franken.de/w/Monitoringseite_eines_Knotens

Dazu würde sich ein "i" (info) Icon anbieten, das FFF-übergreifend verwendet wird. 
Beispielsweise: https://commons.wikimedia.org/wiki/Information

**Comment by adrianschmutzler** [comment]
Duplikat von https://github.com/FreifunkFranken/fff-monitoring/issues/152
