### ISSUE TITLE
Layer-Menü in Monitoring-Karte

### ISSUE THREAD

**Issue by Nautic** [FreifunkFranken/fff-monitoring#165]
Texteiträge verbessern:
alt:
1. Routers
2. Routers V2 und dezentral
3. Hoods
4. Hoods V2
5. Position-Popup

neu:
1. Router V1
2. Router V2 und dezentral
3. Hood V1
4. Hood V2
5. Koordinate-Popup

**Comment by adrianschmutzler** [comment]
Kann man drüber nachdenken. Ggf. mach ich auch die dezentralen noch komplett extra.

Mal sehen, wenn ich Urlaub habe schau ich mal die ganzen Issues durch ...

**Comment by adrianschmutzler** [comment]
Das Menu wurde im Rahmen des Updates (dezentrale Hoods separat) umgestaltet.
Die Benennung habe ich aber abweichend gestaltet, da das Monitoring eigtl. Englisch ist.
