### ISSUE TITLE
Basis-Layer in Monitoring-Karte

### ISSUE THREAD

**Issue by Nautic** [FreifunkFranken/fff-monitoring#166]
Nur OpenStreetMap als Basikarte verwenden.

Andere Optionen löschen, Auswahl-Möglichkeit aus Layer-Menü entfernen.
Das macht das Menü übersichtlicher und simpler.

**Comment by adrianschmutzler** [comment]
Ich verwende selbst nur die Standardkarte. Das ist aber was, wofür man ein Meinungsbild einholen sollte.

Wenn dir das entsprechend wichtig ist, solltest du auf der Mailliste mal eine "Umfrage" starten.

**Comment by adrianschmutzler** [comment]
Habe mich mal damit befasst. Ich werde bis auf weiteres alle drei Optionen beibehalten. Ich finde nicht, dass das Menu dadurch unübersichtlich wird. Tatsächlich haben wir noch üppig Platz (habs jetzt nicht am Handy getestet).

Gerade die dritte Karte ist durchaus interessant, da es sich um eine Geländekarte handelt. Leider muss man den API-Key im Klartext hinterlegen und hat keine Möglichkeit, bei der Console nach Domains o.ä. zu filtern, so wie das z.B. bei Google Maps möglich ist. Da die Karte trotz API-Key-Hinweis nutzbar ist, werde ich sie so belassen. Wenn das irgendwann kaputt geht, kann ich immer noch testweise einen API-Key hinterlegen.

Gerade für Installationen auf dem Land finde ich das Geländerelief interessant.
