### ISSUE TITLE
Nachbarn zeigen integer statt Mac-Adresse bei unbekanntem Gerät

### ISSUE THREAD

**Issue by adrianschmutzler** [FreifunkFranken/fff-monitoring#194]
Für unbekannte Geräte wird die long int statt der MAC-Adresse angezeigt.
=> Conversion ergänzen.

**Comment by adschm** [comment]
Fixed in https://github.com/FreifunkFranken/fff-monitoring/commit/ca7c2ff3b367a3fe432fef2c11b515edc4b9013d
Comments still need to be fixed.
