### ISSUE TITLE
Use a relational DB for structural data and rrd for historical  statistics

### ISSUE THREAD

**Issue by mifritscher** [FreifunkFranken/fff-monitoring#27]
Now, a mongoDB is used for everything, which creates a lot of load because of using BSON. For structural data (hoods, routers, interfaces), a relational DB is much better. MongoDB could be used for complex unstructured data - perhaps config files could be one point. For historical statistics (number of clients, bandwidth etc.), rrd fits way better.

**Comment by adridolf** [comment]
Done by MySQL.
