### ISSUE TITLE
Gelöschte Router in Extra "Hood"

### ISSUE THREAD

**Issue by loki-kun** [FreifunkFranken/fff-monitoring#37]
Hallo,

wäre es möglich die offline Router die nach X Tagen gelöscht werden in eine für Admin Sichtbare Tabelle zu bekommen?

Hintergrund der Frage ist, das man nicht sieht wie ein Router gelöscht worden ist oder ob er nur umbenannt worden ist.

Mir würde Routername Mac-Adresse und Nutzer ja ausreichen und halt ein last seen

**Comment by adridolf** [comment]
Also zunächst wo's steht (für mich):
routertools.py Zeile 170-174

Zur Frage:
Man könnte an der Stelle im Code 1.) einfach von der Routertabelle in eine andere Tabelle kopieren und dann in der ersten löschen oder 2.) die Router in der Tabelle lassen und z.B. den Status auf orphaned setzen.

Letzteres hätte den Vorteil, dass es einfach umzusetzen wäre und man keine zwei identischen Tabellen braucht. Hier müsste man allerdings den Code durchgehen, um dann bei der normalen Anzeige die orphaned routers rauszuschmeißen (was mir aber immer noch lieber wäre).

Wäre interessant, ob asdil dazu eine Meinung hat.

**Comment by asdil12** [comment]
Wenn ein Router umbenannt wurde, steht das im event log. (-> Umbenennung nicht so schnell hinten aus dem log raus fallen lassen?)

Der 2. Vorschlag könnte sich negativ auf die performance (vor allem bei der Statistik Seite) auswirken.

Eine einfache Liste mit routernamen und mac wäre vmtl das einfachste.

**Comment by adridolf** [comment]
Es wurde ein orphaned Status eingeführt, der Router jetzt 180 Tage in der DB behält (und anzeigt). Dies sollte mit MySQL kein Performance-Problem mehr darstellen. Evtl. weite ich den Zeitraum noch aus, aber irgendwann muss auch mal Schluss sein.
