### ISSUE TITLE
wrong connection state due to the caching of tiles

### ISSUE THREAD

**Issue by mojoaxel** [FreifunkFranken/fff-monitoring#6]
It happens that connection state (online/offline) for nodes are displayed false on the map. This is also the case for connections.

This error ist due to the local caching of tiles. It happens for example that the connection state changes while changing the zoom-level.

I strongly would suggest to render the "dots" and "lines" on the client. Leaflet has perfekt support for this. This also would reduce the dependencies on the server, because mapnic would not be needed anymore.
I tried to fix this issue but i could not satisfy all the development-dependencies on my (old) ubuntu system.

_By the way: I'm very happy to see how the map improves and I realy like to use it!_

**Comment by adridolf** [comment]
Since this is very old and caching is important to many users, I close it.
