### ISSUE TITLE
Switch chart scaling between Byte/s and Bit/s

### ISSUE THREAD

**Issue by mojoaxel** [FreifunkFranken/fff-monitoring#8]
Feature-Request:
It would be nice if it would be possible to switch the chart-scale from Byte to Bit per second.

Maybe I can help implementing this, I have some experience with flot.

**Comment by asdil12** [comment]
Do you really think this is a good idea?
I personally find it more intuitive this way. The relation to file sizes makes it easier.

**Comment by mojoaxel** [comment]
The problem ist that e.g. DSL-Connections are messured in Mbit/s. Wireless Devices also descripe their connection speed in bit/s. I honestly was confused the first time seeing the charts.
I would like a switch but could live without :-)

By the way: Why MiB/s and not MB/s ?

**Comment by asdil12** [comment]
> The problem ist that e.g. DSL-Connections are messured in Mbit/s. Wireless Devices also descripe their connection speed in bit/s. I honestly was confused the first time seeing the charts.
> I would like a switch but could live without :-)
I began using Bytes insted of Bits because the routers provide a ByteConter value (that is actually wrongly interpreded as a Bit counter by Netmon).


> By the way: Why MiB/s and not MB/s ?
Because I use 1024 and not 1000 Bytes/K(i)B and KiB per M(i)B.
The MiB "Mibibyte" = MegaBinaryByte values are commonly used in the Linux area so I decided to use them for sake of correctness.

**Comment by mojoaxel** [comment]
Every day you learn something new :-)

**Comment by adridolf** [comment]
@asdil12 : Ich würde eigentlich gerne auf Bit/s statt Bytes/s umstellen. Da hast du natürlich ein Veto!

Umschaltbar ist mir im Moment zu aufwändig ... Wie ist deine Meinung?

**Comment by asdil12** [comment]
Byte/Sekunde ist IMHO eingängiger

**Comment by adridolf** [comment]
Ich habe mal rumgefragt und die Tendenz war eindeutig bei Bit. Werde das heute per Patch umstellen und dann mal sehen, wie die Resonanz ist.
