### ISSUE TITLE
Monitoring-Umzug

### ISSUE THREAD

**Issue by adridolf** [FreifunkFranken/fff-monitoring#82]
Mein MySQL-basierter Monitoring-Clon ist nun soweit, dass er einsatzfähig ist. Der kritische Schritt ist dabei die Nutzer-Datenbank.

Wir müssten also mittels des angehängten Skriptes die UserDB in einen CSV-File schreiben, damit ich die dann wieder ins MySQL einlesen kann.

Falls dies gewünscht/okay/akzeptabel ist, wäre 18.11. nachmittag oder 19.11. den ganzen Tag eine günstige Gelegenheit. Gerne können wir dann auch gleich Zugänge zum neuen Server verteilen ...

http://fff-monitoring.fff.community/

Beste Grüße

Adrian
[users2csv.txt](https://github.com/asdil12/fff-monitoring/files/1480176/users2csv.txt)

**Comment by asdil12** [comment]
Willst du nicht lieber https://monitoring.fff.community/ nehmen?
Das ist nicht so redundant :)

**Comment by asdil12** [comment]
Siehe Mail für CSV.

**Comment by adridolf** [comment]
Ich habe Reddog so verstanden, dass die Domain mit umgezogen werden kann/soll.

Ich will aber jetzt nicht, dass dir das wie eine feindliche Übernahme vorkommt, ist ja dein Projekt :-)

**Comment by asdil12** [comment]
Dann ziehen wir die domain mit um - ich hatte gerade angenommen, freifunk franken sei komplett auf die fff.community domain gewechselt und das sei schon die neue domain.
Und es ist kein Problem - ich komme ja schon seit ewigkeiten nicht dazu, das monitoring auf mysql zu portieren.

**Comment by adridolf** [comment]
Ich hab jetzt erstmal alle Änderungen in meinen Fork geworfen. Ich bin mir noch nicht schlüssig, wie wir das dann weiterführen:
1) Du übernimmst alles in dein Repo
2) Ich führe das Repo bei mir weiter und deins bleibt "alt"
3) Wir machen ein "offizielles" Repo unter Freifunk Franken

**Comment by asdil12** [comment]
Ich würde ein offizielles Repo favorisieren.
Da komme dann mein aktueller Stand in einen v1-branch (oder tag) und der neue Stand in den master-branch.

**Comment by adridolf** [comment]
User sind drauf. Den User ohne Namen hab ich gelöscht.

**Comment by adridolf** [comment]
Hab grade mit reddog gesprochen, wir können auf freifunkfranken mit dem repo umziehen. Das musst scheinbar du anstoßen:
https://help.github.com/articles/about-repository-transfers/
Danach würde ich das Tag setzen und den Rest von mir selbst reinpushen!

**Comment by asdil12** [comment]
"You don’t have the permission to create repositories on FreifunkFranken"

**Comment by adridolf** [comment]
"When the current owner initiates the transfer, the new owner will receive an email giving the option to accept or reject the transfer. If the new owner doesn't accept the transfer within one day, it won't complete."

Gibt es da evtl. noch eine andere Option, die du wählen kannst? Sonst macht die Beschreibung hier irgendwie keinen Sinn...

**Comment by asdil12** [comment]
Transferring to an organization

Users must have repository creation permissions within the receiving organization before they can transfer a repository that they individually own. 

Aus: https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by adridolf** [comment]
Okay. Du kannst mir entweder bei dir kurz owner Rechte geben, wenn du mir genug vertraust. Oder ich rede morgen mit reddog, dass du owner rechte bei freifunk kriegst.

**Comment by asdil12** [comment]
Ich kann dich - glaube ich - nur als Collaborator eintragen.

**Comment by adridolf** [comment]
So, jetzt bist du owner bei freifunk-franken, transferier mal.

**Comment by asdil12** [comment]
done

**Comment by adridolf** [comment]
Danke. Hab dir jetzt den global admin wieder weggenommen, weil das jetzt ohne Absprache war. Auf dem Repo bist du aber weiter Admin.

**Comment by adridolf** [comment]
Fertig. Alles wunderbar!
