### ISSUE TITLE
Add perma-links to router page based on MAC address

### ISSUE THREAD

**Issue by adridolf** [FreifunkFranken/fff-monitoring#90]
If router IDs change, links to a router are destroyed. It is thus desirable to link by the br-mesh MAC address.

For this purpose, I want to create a perma-link displayed at the router-details page.

**Comment by adridolf** [comment]
Any suggestion on how the link should look like are welcome!
- Real Link?
- Link as text?
- ...

**Comment by asdil12** [comment]
Maybe use the router mac directly in the router page url

**Comment by asdil12** [comment]
So we shouldn't add some additional perma-link but change the url of the router-page to include the mac.

**Comment by adridolf** [comment]
I've already thought about this, but:
1. This won't work for routers without br-mesh.
2. Additionally, from a pedantic point-of-view, the router id is the primary and should be used for identification.
So, I tend to be against that at the moment.

**Comment by asdil12** [comment]
Every router should have at least one network interface, which has the
mac address, that is used to identify the existing router in the db when
importing alfred-data.

**Comment by adridolf** [comment]
We have a table 'router' with one entry per router.
We have a table 'router_netif' with one entry per combination of router and netif.

Searching is easy if we know the MAC:
Look for the MAC in router_netif, retrieve the router ID and then look for the router ID in the router table (practically this is done by INNER JOIN).

But the other way around (to calculate the link) it is more complicated:
We know the router, but which MAC should we use?
1. The br-mesh one: See problems above (some Gateways don't have br-mesh)
2. The first one in list: Who guarantees that we do not use a temporary interface for the link
3. A priority list of interfaces to use: Look for br-mesh, if not present use second in list and so on. For me, this looks too complicated for a central feature like the router links.

**Comment by adridolf** [comment]
Für das Wiki gibt es jetzt ein Template: https://wiki.freifunk-franken.de/w/Vorlage:Router

**Comment by adridolf** [comment]
I have now implemented a perma-link to the router page: f61df4cd0bf0a1c7e25711b4dc0d8a60a5634d73

If someone does not like this, feel free to comment.

**Comment by adridolf** [comment]
I just realized that asdil12 mentioned the Alfred sender mac. Maybe one can actually use that, but I'm not sure whether that's a clever way to go.
