### ISSUE TITLE
Für die Meshlinie sollte die beste Verbindung ausgewertet werden

### ISSUE THREAD

**Issue by fblaese** [FreifunkFranken/fff-monitoring#92]
Dieser AP https://monitoring.freifunk-franken.de/routers/4679 sieht seinen Nachbarn sowohl per Ethernet, als auch (durch viele Wände hindurch) per WLAN.
Für die Linie wird die WLAN Verbindung ausgewertet, daher ist diese trotz Ethernetverbindung rot.

**Comment by adridolf** [comment]
Patch wird in ein paar Stunden eingespielt ...

**Comment by fblaese** [comment]
Ich fürchte, das hat irgendwas kaputt gemacht. Jetzt fehlt die Linie zum oben genannten Router nämlich komplett. Möglicherweise hat das auch was mit #96 zu tun?

**Comment by adridolf** [comment]
Poste mal Links zu den verbundenen Routern. Bei mir sieht alles normal aus.
Evtl. vorher mal F5 oder strg+F5 probieren.

**Comment by fblaese** [comment]
https://monitoring.freifunk-franken.de/routers/4679 und http://monitoring.freifunk-franken.de/routers/4639

aktuell ist die Linie auch wieder da, allerdings ist der schwache w2mesh grade weg. Force Reload hatte ich nicht probiert.
