### ISSUE TITLE
Chrome schlägt Übersetzung für Routerliste vor

### ISSUE THREAD

**Issue by fblaese** [FreifunkFranken/fff-monitoring#94]
Die Seite wird von Chrome aus irgendeinem Grund als Dänisch erkannt.

Eine mögliche Lösung wäre, dem Browser mit entsprechenden Metadaten ein wenig zu helfen (siehe #93)
Da die Seite sowohl deutschen, als auch englischen Text enthält, kann auch darüber nachgedacht werden, zusätzlich `<meta name="google" content="notranslate">` einzufügen, um einen Übersetzungsvorschlag von Chrome komplett zu unterdrücken.

**Comment by adridolf** [comment]
Bin für notranslate. Werde mir das bei Gelegenheit nochmal genau anschauen.

**Comment by adridolf** [comment]
Content-Language: c4b4ca27435d3de12d3334676b4c98d2da8f4bc4
NoTranslate: 88284c1c8d6d74bfda60a78ce8fb38c32454b35b
