### ISSUE TITLE
Auf der Karte deaktivierte Router können weiterhin angewählt werden.

### ISSUE THREAD

**Issue by fblaese** [FreifunkFranken/fff-monitoring#95]
Deaktiviert man Router auf der Karte, können sie weiterhin angeklickt und ausgewählt werden, das entsprechende Popup taucht dann auch auf.

Das ist vor allem bei weit herausgezoomter Karte etwas unpraktisch, hat aber keine Dringlichkeit.

**Comment by adridolf** [comment]
Das sind zwei völlig unterschiedliche Mechanismen (Layer und Popup) und richtig hässlich, das unter einen Hut zu bringen.

**Comment by adridolf** [comment]
Erledigt. Bitte testen und Feedback geben.

Vorher Strg+F5!
